# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantismo < Formula
  desc "Eyes on every agent — a personal firewall for AI agents"
  homepage "https://github.com/abidkhan1974/mantismo"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abidkhan1974/mantismo/releases/download/v0.1.0/mantismo_0.1.0_darwin_amd64.tar.gz"
      sha256 "ebba2aa7628472c00a01a7f94ffece8b3a04d6ab566e15f837ddb17495d3383a"

      define_method(:install) do
        bin.install "mantismo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abidkhan1974/mantismo/releases/download/v0.1.0/mantismo_0.1.0_darwin_arm64.tar.gz"
      sha256 "0611a5f25cedeb77bada33aac666a6fa8694cf8afa1672295c3e52882bb5ff58"

      define_method(:install) do
        bin.install "mantismo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abidkhan1974/mantismo/releases/download/v0.1.0/mantismo_0.1.0_linux_amd64.tar.gz"
      sha256 "ff2b9bf62329ab50e031320960a8ebecd922c516c4db618f059e8b402225d94d"
      define_method(:install) do
        bin.install "mantismo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abidkhan1974/mantismo/releases/download/v0.1.0/mantismo_0.1.0_linux_arm64.tar.gz"
      sha256 "4982f5e2870276a9d89b8a73d4a3860d4f3d00be9b986d9043d632f726a46fdd"
      define_method(:install) do
        bin.install "mantismo"
      end
    end
  end

  test do
    system "#{bin}/mantismo", "--version"
  end
end
