# This file was generated by GoReleaser. DO NOT EDIT.
cask "mantismo" do
  name "mantismo"
  desc "Eyes on every agent — a personal firewall for AI agents"
  homepage "https://github.com/abidkhan1974/mantismo"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mantismo"

  on_macos do
    on_intel do
      url "https://github.com/abidkhan1974/mantismo/releases/download/v#{version}/mantismo_#{version}_darwin_amd64.tar.gz"
      sha256 "515b12a1ebeadc615d7ada5ab4dcad19b0b469d99001c1ae5bf2dbcf63b54546"
    end
    on_arm do
      url "https://github.com/abidkhan1974/mantismo/releases/download/v#{version}/mantismo_#{version}_darwin_arm64.tar.gz"
      sha256 "836a57b9f6a73c7f0fa0dc3eaf3a29ae7911e5ab213c1ab7aa8b7cd0a69aa121"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abidkhan1974/mantismo/releases/download/v#{version}/mantismo_#{version}_linux_amd64.tar.gz"
      sha256 "b7e84d07cdd528df826294557f4d6124053aa9d1ca4a5a51b0a509d3fc135a96"
    end
    on_arm do
      url "https://github.com/abidkhan1974/mantismo/releases/download/v#{version}/mantismo_#{version}_linux_arm64.tar.gz"
      sha256 "615a24721de575095f241754557375994890f8f5932c2e8d9b3a1c1fbb75e4f9"
    end
  end

  # No zap stanza required
end
